controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(assets.image`fireball`, ship, 0, -140)
    projectile.startEffect(effects.smiles, 100)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    sprite.destroy()
    otherSprite.destroy(effects.fire)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    scene.cameraShake(5, 500)
    otherSprite.destroy(effects.ashes)
    sprite.startEffect(effects.fire, 200)
    info.changeLifeBy(-1)
})
let projectile: Sprite = null
let ship: Sprite = null
music.play(music.stringPlayable("C5 A B G A F G E ", 120), music.PlaybackMode.LoopingInBackground)
let asteroids = [
img`
    . . . . . . . . . . b 5 b . . . 
    . . . . . . . . . b 5 b . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 5 d f . . 
    . . . . b 5 5 1 f f 5 d 4 c . . 
    . . . . b 5 5 d f b d d 4 4 . . 
    . b b b d 5 5 5 5 5 4 4 4 4 4 b 
    b d d d b b d 5 5 4 4 4 4 4 b . 
    b b d 5 5 5 b 5 5 5 5 5 5 b . . 
    c d c 5 5 5 5 d 5 5 5 5 5 5 b . 
    c b d c d 5 5 b 5 5 5 5 5 5 b . 
    . c d d c c b d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    . . . . . . . . . . . . . . . . 
    `,
img`
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . . . . . . . . 
    . . . . . . . . . b 5 5 b . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . b b b b b 5 5 5 5 5 5 5 b . . 
    . b d 5 b 5 5 5 5 5 5 5 5 b . . 
    . . b 5 5 b 5 d 1 f 5 d 4 f . . 
    . . b d 5 5 b 1 f f 5 4 4 c . . 
    b b d b 5 5 5 d f b 4 4 4 4 b . 
    b d d c d 5 5 b 5 4 4 4 4 4 4 b 
    c d d d c c b 5 5 5 5 5 5 5 b . 
    c b d d d d d 5 5 5 5 5 5 5 b . 
    . c d d d d d d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `,
img`
    . . . . . . . . . b 5 b . . . . 
    . . . . . . . . . b 5 b . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 b c 5 5 d 4 c . . 
    . b b b b 5 5 5 b f d d 4 4 4 b 
    . b d 5 b 5 5 b c b 4 4 4 4 b . 
    . . b 5 5 b 5 5 5 4 4 4 4 b . . 
    . . b d 5 5 b 5 5 5 5 5 5 b . . 
    . b d b 5 5 5 d 5 5 5 5 5 5 b . 
    b d d c d 5 5 b 5 5 5 5 5 5 b . 
    c d d d c c b 5 5 5 5 5 5 5 b . 
    c b d d d d d 5 5 5 5 5 5 5 b . 
    . c d d d d d d 5 5 5 5 5 d b . 
    . . c b d d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `,
img`
    . . . . . . . . . . b 5 b . . . 
    . . . . . . . . . b 5 b . . . . 
    . . . . . . b b b b b b . . . . 
    . . . . . b b 5 5 5 5 5 b . . . 
    . . . . b b 5 d 1 f 5 d 4 c . . 
    . . . . b 5 5 1 f f d d 4 4 4 b 
    . . . . b 5 5 d f b 4 4 4 4 b . 
    . . . b d 5 5 5 5 4 4 4 4 b . . 
    . . b d d 5 5 5 5 5 5 5 5 b . . 
    . b d d d d 5 5 5 5 5 5 5 5 b . 
    b d d d b b b 5 5 5 5 5 5 5 b . 
    c d d b 5 5 d c 5 5 5 5 5 5 b . 
    c b b d 5 d c d 5 5 5 5 5 5 b . 
    . b 5 5 b c d d 5 5 5 5 5 d b . 
    b b c c c d d d d 5 5 5 b b . . 
    . . . c c c c c c c c b b . . . 
    `,
img`
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ................................
    ........ccccc...................
    ......ccbbbbbc..................
    ....ccddbbbbbbf.................
    ...cbbbddbbffbf.................
    ....ffffdbbffbff................
    .......fbbbbbbbf................
    .......fbbbbbbbff...............
    ......ffbbbbbbbbfff.............
    ......f6bbbbbb663ddcc...........
    .....cc66bbbb666dddddc..........
    .....cd36666663dddddddc.........
    .....cddd3333dbddddddbcc........
    .....cddddddddbdddddbbddc.......
    .....cddddddddbbdddbbdddbc......
    ......cddddddddbbdbbddddbbccc...
    ......ccddddddddbbbbcccccbbbcc..
    .......ccddddddddddddddbccffff..
    ........cccbddccbddddbbfff......
    ........c333bb333cbbfff.........
    ........c33cc33cc3fff...........
    `,
img`
    ............................................................cc.....
    ...........................................................ccc.....
    ...........................................................cdc.....
    ..........................................................ccdc.....
    ..........................................................cddcc....
    .........................................................ccddbcc...
    .........................................................cdddbcc...
    ........................................................ccdddbdc...
    .......................................................ccdddbddc...
    ......................................................ccdddbbddbcc.
    ....................................................ccbbddbbdddbdc.
    ..................................................cccddbddddddbddc.
    .................................................ccddddbdddddbdddcc
    ................................................cdddddbbddddddddbcc
    ccc............................................cdddddbbddddddddbddc
    cdcc..........................................cddddddbbddddddbbddcc
    cddcc........................................cddddddddbbdddddddddc.
    .cddcc.......................................cdddddddddbddddddddc..
    .cdddcc......................................cdddddddddbdddddbbbccc
    ccbdddc......................................cbdddddddbbddddddddddc
    cdbbddcc.................ccccccc.............cbdddddbbbddddddddddcc
    cddbbddc...............ccbbbbbbbcc............cdddddbbddddddddddcc.
    ccdddddcc.............ccbbbbbbbbbcc...........cdddddbbddddddbbbbc..
    .cddddddcc............cbbbbbbbbbbbc...........cddddddbdddddddbbbc..
    .ccddddddcc...........cbbbbbbffbbbcc.........cbddddddbddddddddddc..
    ..cddddddbccccccc....c111bbbbffbbbbcc......cccddddddbbddddbbdddcc..
    ...cddddbbdddddddcc..f111bbbbbbbbbbbccc..ccddddddbbbbdddddddbbbc...
    ..cbbbddbbddddddddcccfbb11cbbbbbbbbbbbcccddddddddbbdddddbdddddc....
    .cdddbbdbbbbdddddddddfbbbbcbbbbbbbbbbb6cdddddddddbdddddddbdddc.....
    .ccdddddddbbbddddddddfbbfccbbbbbbbbbbb6cdddbbbbdbbddddddddbbbc.....
    ..ccddddddddbddddddddfbfdcbbbbbbbbbbb66bddbbbdbbbbddbddbdddbc......
    ....cddddddbbddddddddffddcbbbbbbbbbbb663bbbdddddddddbddbbdddc......
    ....cbbddddbbdbbbddddddddcbbbbbbbbbbb663bbbddbdddddddbddbbbcc......
    ....cddbbdddbbbbbddddddddcbbbbbbbbb66633ddbddbdddbbdddbddccc.......
    ....ccddddddddddbdddddddccbbbbbbbbb6633dddbddbbdddbbddcccc.........
    .....ccdddddddddbbddbbddcbbbbbbbbbb663dddddddcbbdddbbc.............
    ......ccddddddddbbbbbbddc6bbbbbbbb666ddddddcccccccccc..............
    .......ccbbbbdddddddbbbbc666bb6666663ddddddc.......................
    .........cbbddddddddddbbc66666666663dddddddc.......................
    .........cdddddbddddddbccd3666633ddddddddddc.......................
    .........ccddbbbddbdddbccdd33333dddddddddddc.......................
    ..........cccccddbbddbb.ccddddddddddddddddddc......................
    ..............ccccccbb...ccdddddddddddddddddc......................
    ...................cc.....ccddddddddddddddddcc.....................
    ...........................ccddddddddddbbbbddcc....................
    ............................bbbdddddddbbbbbddccccccc...............
    .............................bbbddddddbdddddddddddbcc..............
    .............................ccccddddbccccddddddddbbc..............
    ............................c3333cdddc3333cddddddcccc..............
    ...........................cc33333cbcc33333cdddddcc................
    ...........................c3333333cc3333333cdcdbbc................
    ...................bbbbbbbbc3c3c3c3cc3c3c3c3cdccbbc................
    ...................b1d11111c3c3c3cb1c3c3c3cbbdbccc.................
    ...................b1dd11111bcbccc111bcbcccdbbbcc..................
    ...................b11d111111111111111dd111dbccc...................
    ..................b111dd1111111111111dd1111dbc.....................
    ..................b1111dd11111111111dd1111ddb......................
    ..................b11111dd111111111dd11111ddb......................
    .................b1111111d11111111dd111111ddb......................
    .................b1111111dd111111dd1111111db.......................
    .................b11111111dd111ddd11111111db.......................
    .................b111111111dd1dd1111111111db.......................
    ................b11111111111ddd1111111111ddb.......................
    ................b111111111111111111111111ddb.......................
    ................b111111111111111111111111ddb.......................
    ................b111111111111111111111111ddb.......................
    ................bbbb111111111111111111111db........................
    ...................bbbbbbb111111111111111db........................
    ..........................bbbbbbbb1111111db........................
    .................................bbbbbbbbbb........................
    `
]
ship = sprites.create(assets.image`dragon`, SpriteKind.Player)
ship.setStayInScreen(true)
ship.bottom = 120
controller.moveSprite(ship, 100, 100)
info.setLife(5)
effects.starField.startScreenEffect()
game.onUpdateInterval(500, function () {
    projectile = sprites.createProjectileFromSide(asteroids[randint(0, asteroids.length - 1)], 0, 75)
    projectile.setKind(SpriteKind.Enemy)
    projectile.x = randint(10, 150)
})
